export const LOCATION_FETCHING = "LOCATION_FETCHING";
export const LOCATION_FETCHED = "LOCATION_FETCHED";
export const LOCATION_FETCHED_FAIL = "LOCATION_FETCHED_FAIL"


export const CURRENT_WEATHER_FETCHING = "CURRENT_WEATHER_FETCHING";
export const CURRENT_WEATHER_FETCHED = "CURRENT_WEATHER_FETCHED";
export const CURRENT_WEATHER_FETCH_FAIL = "CURRENT_WEATHER_FETCH_FAIL";


export const FIVE_DAYS_WEATHER_FETCHING = "FIVE_DAYS_WEATHER_FETCHING";
export const FIVE_DAYS_WEATHER_FETCHED = "FIVE_DAYS_WEATHER_FETCHED";
export const FIVE_DAYS_WEATHER_FETCH_FAIL = "FIVE_DAYS_WEATHER_FETCH_FAIL";


export const AIR_POLLUTION_WEATHER_FETCHING = "AIR_POLLUTION_WEATHER_FETCHING";
export const AIR_POLLUTION_WEATHER_FETCHED = "AIR_POLLUTION_WEATHER_FETCHED";
export const AIR_POLLUTION_WEATHER_FETCH_FAIL = "AIR_POLLUTION_WEATHER_FETCH_FAIL";



export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
